CREATE TABLE IF NOT EXISTS "Product" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "price" INTEGER NOT NULL,
  "image" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "story" TEXT NOT NULL,
  "longevity" TEXT NOT NULL,
  "projection" TEXT NOT NULL,
  "occasion" TEXT NOT NULL,
  "topNotes" TEXT NOT NULL,
  "middleNotes" TEXT NOT NULL,
  "baseNotes" TEXT NOT NULL,
  "ingredients" TEXT NOT NULL,
  "character" TEXT NOT NULL,
  "targetUser" TEXT NOT NULL,
  "shopeeUrl" TEXT,
  "tiktokUrl" TEXT,
  "isFeatured" INTEGER NOT NULL DEFAULT 0,
  "isBestSeller" INTEGER NOT NULL DEFAULT 0,
  "isLimitedEdition" INTEGER NOT NULL DEFAULT 0,
  "isSignatureCollection" INTEGER NOT NULL DEFAULT 0,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
