INSERT INTO "Product" (
  "id","name","price","image","description","story","longevity","projection","occasion",
  "topNotes","middleNotes","baseNotes","ingredients","character","targetUser",
  "shopeeUrl","tiktokUrl","isFeatured","isBestSeller","isLimitedEdition","isSignatureCollection"
) VALUES
(
  'prod_velvet_rose',
  'Velvet Rose',
  2490000,
  'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=1400&q=80',
  'Velvet Rose adalah parfum dengan sentuhan floral elegan yang memberikan kesan mewah dan romantis.',
  'Dirancang untuk malam yang berkelas, Velvet Rose memadukan nuansa bunga halus dengan jejak musk hangat yang anggun.',
  '8-12 jam',
  'Soft namun berkelas',
  'Acara formal, dinner, dan evening event',
  'Rose, Citrus',
  'Jasmine, Peony',
  'Musk, Amber',
  'Essential oil premium dari Perancis',
  'Floral, sweet, oriental',
  'Wanita',
  'https://shopee.co.id/',
  'https://www.tiktok.com/',
  1,1,0,1
),
(
  'prod_noir_eclat',
  'Noir Éclat',
  2790000,
  'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=1400&q=80',
  'Noir Éclat menghadirkan karakter woody oriental untuk persona percaya diri dan modern.',
  'Komposisi intens yang dibuka segar lalu berkembang menjadi kayu hangat berlapis amber, meninggalkan kesan eksklusif.',
  '10-14 jam',
  'Kuat di awal, lembut di dry-down',
  'Meeting penting, event malam, special occasion',
  'Bergamot, Black Pepper',
  'Iris, Saffron',
  'Oud, Sandalwood, Amber',
  'Natural oil blend dan imported fragrance concentrate',
  'Woody, spicy, oriental',
  'Pria',
  'https://shopee.co.id/',
  'https://www.tiktok.com/',
  0,1,1,0
),
(
  'prod_citrine_blanc',
  'Citrine Blanc',
  2290000,
  'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=1400&q=80',
  'Citrine Blanc memancarkan kesegaran bersih dengan sentuhan creamy musk yang refined.',
  'Wangi yang ringan namun berkarakter untuk gaya hidup aktif, menghadirkan aura polished dari pagi hingga malam.',
  '7-10 jam',
  'Moderate',
  'Daily premium wear, brunch, business casual',
  'Lemon, Neroli',
  'White Tea, Orange Blossom',
  'White Musk, Cedar',
  'Essential oil citrus Mediterranean dan white musk accord',
  'Fresh, clean, musky',
  'Unisex',
  'https://shopee.co.id/',
  'https://www.tiktok.com/',
  0,0,0,1
);
